/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class JdArchivoTxt extends javax.swing.JDialog {

    String rutaAlma = "C:/Users/Usuario/Documents/docArchProSisOper/";
    public JdArchivoTxt(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /**
     * metodo enacrgado de crear y almacenar los valores en una archivo txt
     * @param titulo: el titulo del archivo 
     * @param contenido: el contenido que se va a almacenar
     * @return un true si se guarda con exito de lo contrario un false
     */
    public  boolean crearArchivo(String titulo,String contenido) {
        try {
            PrintWriter writer = new PrintWriter(rutaAlma+titulo+".txt", "UTF-8");
            String[] allcontenido = contenido.split("/n");
            System.out.println("con=====>: "+allcontenido.toString());
            for(String cont : allcontenido)
            {
                writer.println(cont);
            }            
            //writer.println("Segunda línea");
            writer.close();
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "¡¡¡Error, no se creo el archivo");
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JTextField();
        txtContenido = new java.awt.TextArea();
        lblIconTxt = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setBackground(new java.awt.Color(255, 255, 255));
        txtTitulo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 355, 71));

        txtContenido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtContenido.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(txtContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1310, 520));

        lblIconTxt.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\ProyectoSistemasOper\\src\\main\\java\\image\\iconTxt.png")); // NOI18N
        getContentPane().add(lblIconTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnSave.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\ProyectoSistemasOper\\src\\main\\java\\image\\iconSave.png")); // NOI18N
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 660, -1, -1));

        btnCancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\ProyectoSistemasOper\\src\\main\\java\\image\\iconCancel.png")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 660, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed

    }//GEN-LAST:event_txtTituloActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String titulo, cajaTexto;
        cajaTexto = txtContenido.getText();
        titulo = txtTitulo.getText();
        //System.out.println("titulo: "+titulo+"/n"+"contenido"+cajaTexto);
        boolean siCreoTxt = crearArchivo(titulo,cajaTexto);
        System.out.println("estado: "+siCreoTxt);
        //FALTA crear archivo txt
        this.setVisible(false);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblIconTxt;
    private java.awt.TextArea txtContenido;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
