/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class JdEjecutar extends javax.swing.JDialog {

    /**
     * Creates new form JdEjecutar
     */
    public int proceso = 0;
    public static int DEFAULT = 0;
    public static int LISTAR_DIRECTORIO=1;
    public static int CREAR_DIRECTORIO=2;
    public static int ELIMINAR_DIRECTORIO=3;
    public String rutaDatos;
    private String rutaDefect = "C:/Users/Usuario/Documents/docArchProSisOper/";
    
    public JdEjecutar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlmComan = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("C:\\Users\\Usuario\\Documents\\docArchProSisOper");
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        txtAlmComan.setBackground(new java.awt.Color(0, 0, 0));
        txtAlmComan.setColumns(20);
        txtAlmComan.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        txtAlmComan.setForeground(new java.awt.Color(255, 255, 255));
        txtAlmComan.setRows(5);
        txtAlmComan.setText("presione la tecla 'CTRL' para ejecutar las sentencias");
        txtAlmComan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAlmComanKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtAlmComan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAlmComanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlmComanKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_CONTROL)
        {
            String textIni = "\n@User{Robin}>";
            String cadAct = this.txtAlmComan.getText();
            this.txtAlmComan.setText(cadAct+textIni);
            if(cadAct.indexOf("@") != -1)
            {
                String[] vecCom = cadAct.split("\n");
                //System.out.println("vec=>"+vecCom[vecCom.length-1]);
                String ultimSent = vecCom[vecCom.length-1];
                ultimSent = ultimSent.substring(ultimSent.indexOf(">")+1, ultimSent.length());                
                System.out.println("###"+ultimSent);
                switch(ultimSent){
                    case("dir") : 
                        this.proceso = LISTAR_DIRECTORIO;
                        JFileChooser fileChooser = new JFileChooser(rutaDefect);
                        fileChooser.showOpenDialog(fileChooser);
                        String rutaArchivo = fileChooser.getSelectedFile().getAbsolutePath();
                        System.out.println("ruta: "+rutaArchivo);
                        this.rutaDatos = rutaArchivo; 
                        break;
                        
                     case("clear dir"):   
                        this.proceso = ELIMINAR_DIRECTORIO;
                        String nombreA = JOptionPane.showInputDialog("nombre de la carpeta a eliminar");
                        File direElim = new File(rutaDefect+nombreA);
                        if(direElim.delete()) System.out.println("elimino carpeta");                            
                        break;
                     case("create dir") : 
                        this.proceso = CREAR_DIRECTORIO;
                        String nombreArch = JOptionPane.showInputDialog("nombre de la carpeta a crear");
                        File directorio = new File(rutaDefect+nombreArch);
                        if(directorio.mkdir()) System.out.println("creado");
                        else System.out.println("no creado");
                        break;
                     case("cls"):
                         txtAlmComan.setText("");
                         this.txtAlmComan.setText("presione la tecla 'CTRL' para ejecutar las sentencias\n");
                         proceso = DEFAULT;                         
                         break;
                        //limpiar pantalla
                    case("exit"):
                        proceso = DEFAULT;
                        dispose();
                     default:
                         this.txtAlmComan.setText(cadAct+textIni+"\nError, comando desconocido"+textIni);
                         proceso= DEFAULT;
                         //lanzar error
                }                    
            }
                        
            
        }
        
        
    }//GEN-LAST:event_txtAlmComanKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdEjecutar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdEjecutar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdEjecutar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdEjecutar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdEjecutar dialog = new JdEjecutar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAlmComan;
    // End of variables declaration//GEN-END:variables
}
