/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visual;


import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Usuario
 */
public class JdOpSis extends javax.swing.JDialog {
        
    private String opcionSelect = "";

    /** Creates new form JdOpcionesSistema */
    public JdOpSis(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearUsu = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnCambiarUsu = new javax.swing.JButton();
        lblImageFondo = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        btnCrearUsu.setText("crear usuario");
        btnCrearUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuActionPerformed(evt);
            }
        });

        btnApagar.setText("apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnCambiarUsu.setText("cambiar usuario");
        btnCambiarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarUsuActionPerformed(evt);
            }
        });

        lblImageFondo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblImageFondo.setText("seleccione la opcion que desea ejecutar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImageFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApagar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearUsu)
                        .addGap(18, 18, 18)
                        .addComponent(btnCambiarUsu)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(lblImageFondo)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearUsu)
                    .addComponent(btnApagar)
                    .addComponent(btnCambiarUsu))
                .addGap(131, 131, 131))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        
    }//GEN-LAST:event_closeDialog

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        opcionSelect = "apagar";
        dispose();
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnCrearUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuActionPerformed
        opcionSelect = "crearUsuario";
        dispose();
    }//GEN-LAST:event_btnCrearUsuActionPerformed

    private void btnCambiarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarUsuActionPerformed
        opcionSelect = "cambiarUsuario";
        dispose();
    }//GEN-LAST:event_btnCambiarUsuActionPerformed
    
    /**
     * metodo encargado de devolver la opcion selecionada
     * @return un string con la opcion que selecciono
     */
    public String getOpcionSelect()
    {
        return this.opcionSelect;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnCambiarUsu;
    private javax.swing.JButton btnCrearUsu;
    private javax.swing.JLabel lblImageFondo;
    // End of variables declaration//GEN-END:variables

    
}
