/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class JfInicio extends javax.swing.JFrame {

    JfVentana ventana;
    private String rutaDatos = "";
    private JpArchivoTxt archivoText = null;
    
    
    public JfInicio(JfVentana ventana) {
        this.setBounds(0, 0, 1366, 768);
        initComponents();
        this.ventana = ventana;                
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnArcTxt = new javax.swing.JButton();
        btnCarpeta = new javax.swing.JButton();
        lblImageIni = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuInformacion = new javax.swing.JMenu();
        mnuProgramas = new javax.swing.JMenuItem();
        mnuOpciones = new javax.swing.JMenuItem();
        mnuAcercaDe = new javax.swing.JMenuItem();
        mnuEjecutar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\ProyectoSistemasOper\\src\\main\\java\\image\\iconCarpeta.png")); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 50, 50));

        btnArcTxt.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\ProyectoSistemasOper\\src\\main\\java\\image\\iconTxt.png")); // NOI18N
        btnArcTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArcTxtActionPerformed(evt);
            }
        });
        getContentPane().add(btnArcTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, 60));

        btnCarpeta.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\ProyectoSistemasOper\\src\\main\\java\\image\\iconCarpeta.png")); // NOI18N
        btnCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarpetaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, 50));

        lblImageIni.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\ProyectoSistemasOper\\src\\main\\java\\image\\imageInicio.jpg")); // NOI18N
        getContentPane().add(lblImageIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -40, 1370, 780));

        jMenuBar2.setBackground(new java.awt.Color(51, 51, 51));

        mnuInformacion.setBorder(null);
        mnuInformacion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\ProyectoSistemasOper\\src\\main\\java\\image\\iconConfig.png")); // NOI18N
        mnuInformacion.setMaximumSize(new java.awt.Dimension(49, 100));
        mnuInformacion.setMinimumSize(new java.awt.Dimension(30, 30));
        mnuInformacion.setPreferredSize(new java.awt.Dimension(33, 40));

        mnuProgramas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnuProgramas.setText("Programas");
        mnuProgramas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProgramasActionPerformed(evt);
            }
        });
        mnuInformacion.add(mnuProgramas);

        mnuOpciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuOpciones.setText("Opciones");
        mnuOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpcionesActionPerformed(evt);
            }
        });
        mnuInformacion.add(mnuOpciones);

        mnuAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mnuAcercaDe.setText("Acerca del sistema");
        mnuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcercaDeActionPerformed(evt);
            }
        });
        mnuInformacion.add(mnuAcercaDe);

        mnuEjecutar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mnuEjecutar.setText("Ejecutar");
        mnuEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEjecutarActionPerformed(evt);
            }
        });
        mnuInformacion.add(mnuEjecutar);

        jMenuBar2.add(mnuInformacion);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcercaDeActionPerformed
        JdAcercaDe acercaDe = new JdAcercaDe(this, true);
        acercaDe.setVisible(true);
        
    }//GEN-LAST:event_mnuAcercaDeActionPerformed
    /**
     * opcion del menu encargada de validar que opcion se seleccion el el jdialog
     * y se ejecutara en este frame
     * @param evt 
     */
    private void mnuOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpcionesActionPerformed
        JdOpSis opcionesSis = new JdOpSis(this,true);
        opcionesSis.setVisible(true);
        String opc = opcionesSis.getOpcionSelect();
        System.out.println("opcion select: "+opc);
        
        if(opc.equals("apagar"))
        {
            System.exit(0);
        }
        else if(opc.equals("crearUsuario"))
        {
            JdCrearUsuario crearUsu = new JdCrearUsuario(this, true);
            crearUsu.setVisible(true);
        }
        else if(opc.equals("cambiarUsuario"))
        {
            this.setVisible(false);
            ventana.setVisible(true);
            ventana.pantallaPrin();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "¡¡¡Error, no se seleccion opcion");
        }
         
    }//GEN-LAST:event_mnuOpcionesActionPerformed

    private void mnuProgramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProgramasActionPerformed
        listarArchivos();
    }//GEN-LAST:event_mnuProgramasActionPerformed

    private void btnCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarpetaActionPerformed
        listarArchivos();
    }//GEN-LAST:event_btnCarpetaActionPerformed

    private void btnArcTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArcTxtActionPerformed
        //System.out.println("presiono boton");      
        JdArchivoTxt archivoTxt = new JdArchivoTxt(this, true);
        archivoTxt.setVisible(true);
        
                
    }//GEN-LAST:event_btnArcTxtActionPerformed
    
    private void mnuEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEjecutarActionPerformed
        JdEjecutar ejecutar = new JdEjecutar(this, true);
        ejecutar.setVisible(true);
        int opcion = ejecutar.proceso;
    }//GEN-LAST:event_mnuEjecutarActionPerformed
    public void listarArchivos()
    {
        JFileChooser fileChooser = new JFileChooser("C:/Users/Usuario/Documents/docArchProSisOper");
        fileChooser.showOpenDialog(fileChooser);
        String rutaArchivo = fileChooser.getSelectedFile().getAbsolutePath();
        System.out.println("ruta: "+rutaArchivo);
        this.rutaDatos = rutaArchivo; 
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArcTxt;
    private javax.swing.JButton btnCarpeta;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel lblImageIni;
    private javax.swing.JMenuItem mnuAcercaDe;
    private javax.swing.JMenuItem mnuEjecutar;
    private javax.swing.JMenu mnuInformacion;
    private javax.swing.JMenuItem mnuOpciones;
    private javax.swing.JMenuItem mnuProgramas;
    // End of variables declaration//GEN-END:variables
}
