/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import BaseDeDatos.ConexionOracle;
import java.util.LinkedList;

/**
 *
 * @author Usuario
 */
public class JpLogin extends javax.swing.JPanel {

    JfVentana ventana;
    public JpLogin(JfVentana ventana) {
        initComponents();
        this.ventana = ventana;
    }
    /**
     * metodo encargado de validar la clave del login
     * @return retorna un true si la contraseña es valida, de lo contrario un false
     */
    public boolean getValLogin()
    {
        String user = this.ctxLoginName.getText();
        String passw = this.ctxLoginPassword.getText();
        //buscar en la base de datos
        ConexionOracle conexion = new ConexionOracle();
        String consulta  = "select * from usuarios";
        System.out.println("consulta: "+consulta);
        LinkedList <String> resultado = conexion.consulUsuarios(consulta);
        System.out.println("tamaño: "+resultado.size());
        boolean estUser=false, estPass= false;
        for(String dato : resultado)
        {
            if(dato.equals(user)) estPass = true;
            if(dato.equals(passw)) estUser = true;
        }
        if(estUser == true && estPass == true)
        {
            return  true;            
        }        
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        ctxLoginName = new javax.swing.JTextField();
        String dirImage = "C:\\Users\\Usuario\\Documents\\NetBeansProjects\\ProyectoSistemasOper\\src\\main\\java\\image\\imageUsuario.png";
        lblImageUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ctxLoginPassword = new javax.swing.JPasswordField();
        lblImageLogin = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setLayout(null);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin);
        btnLogin.setBounds(640, 530, 120, 50);

        ctxLoginName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxLoginNameActionPerformed(evt);
            }
        });
        add(ctxLoginName);
        ctxLoginName.setBounds(530, 380, 360, 40);

        lblImageUsuario.setIcon(new javax.swing.ImageIcon(dirImage));
        add(lblImageUsuario);
        lblImageUsuario.setBounds(590, 110, 220, 140);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Contraseña");
        add(jLabel1);
        jLabel1.setBounds(390, 430, 131, 50);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Usuario");
        add(jLabel2);
        jLabel2.setBounds(390, 360, 90, 60);

        ctxLoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxLoginPasswordActionPerformed(evt);
            }
        });
        add(ctxLoginPassword);
        ctxLoginPassword.setBounds(530, 440, 360, 40);

        lblImageLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\ProyectoSistemasOper\\src\\main\\java\\image\\imageLogin.jpg")); // NOI18N
        add(lblImageLogin);
        lblImageLogin.setBounds(0, 0, 1360, 770);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        this.ventana.pantallaIni();
        System.out.println("holla persiono el boton");
    }//GEN-LAST:event_btnLoginActionPerformed

    private void ctxLoginNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxLoginNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxLoginNameActionPerformed

    private void ctxLoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxLoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxLoginPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JTextField ctxLoginName;
    private javax.swing.JPasswordField ctxLoginPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblImageLogin;
    private javax.swing.JLabel lblImageUsuario;
    // End of variables declaration//GEN-END:variables
}
